In [1]:
#inverse of a complex matrix and solution 

In [1]:
import numpy as np

In [2]:
N = 10

In [3]:
A = np.random.rand(N,N) + np.random.rand(N,N)*1j
B = np.random.rand(N) +  + np.random.rand(N)*1j

In [4]:
A

array([[0.78714714+0.05784141j, 0.42070314+0.00751223j,
        0.64372384+0.79480513j, 0.97661792+0.39857661j,
        0.10274636+0.47994492j, 0.38258114+0.92538535j,
        0.98650475+0.76153967j, 0.30069962+0.99642943j,
        0.45447317+0.07697588j, 0.22845139+0.80820981j],
       [0.51795929+0.31625463j, 0.1019688 +0.83537281j,
        0.20371422+0.39516361j, 0.32918868+0.53501359j,
        0.8922126 +0.85580128j, 0.79011885+0.14780797j,
        0.11313608+0.53327646j, 0.41355676+0.79548541j,
        0.59031673+0.970147j  , 0.36207785+0.72920085j],
       [0.19902026+0.91992913j, 0.06606744+0.59119919j,
        0.59249906+0.58982232j, 0.04094204+0.37643447j,
        0.76546255+0.16114797j, 0.14892007+0.93394953j,
        0.40488339+0.63297295j, 0.33140043+0.77552284j,
        0.79390351+0.09095265j, 0.53558946+0.6242168j ],
       [0.34868936+0.79520764j, 0.33153522+0.5823609j ,
        0.57311274+0.47830545j, 0.32417407+0.15679549j,
        0.23611623+0.28680418j, 0.9827208 +0.

In [25]:
A_inv = np.linalg.inv(A)

In [28]:
x = np.matmul(A_inv, B)
print(x)

[ 0.55356358-0.10884089j  0.97331654+0.5752536j  -0.56295051-0.26296578j
  0.29288593+0.09098898j -0.18335936+0.26952806j  0.06297466+0.85595456j
 -0.0251466 +0.08450837j -0.14544596+0.19259862j  0.41543877-0.44493465j
 -0.21772336-1.05089995j]


In [29]:
x.real

array([ 0.55356358,  0.97331654, -0.56295051,  0.29288593, -0.18335936,
        0.06297466, -0.0251466 , -0.14544596,  0.41543877, -0.21772336])

In [31]:
x.imag

array([-0.10884089,  0.5752536 , -0.26296578,  0.09098898,  0.26952806,
        0.85595456,  0.08450837,  0.19259862, -0.44493465, -1.05089995])

In [32]:
abs(x)

array([0.56416219, 1.1306024 , 0.62134071, 0.30669392, 0.32598471,
       0.85826803, 0.08817038, 0.24134779, 0.60873328, 1.07321674])