In [22]:
import numpy as np

In [23]:
A = np.array([[2,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,-2,1,3]],float)

In [24]:
B = np.array([-4,3,9,7],float)
N = len(B)

In [25]:
# Gaussian elimination

#m corresponds to the row number 0 to N-1 
for m in range(N):
    
        #Partial pivoting step. 
        #interchange rows if necessary here        
        
        #Divide by the diagonal element
        div = A[m,m]
        A[m,:] = A[m,:] / div
        B[m] = B[m] / div
        
        #Now subtract this modified row from the lower rows
        for i in range(m+1,N):
            mult = A[i,m]
            A[i,:] = A[i,:] - A[m,:]*mult
            B[i] = B[i] - B[m]*mult
            
#Now we have converted A to a lower triangular matrix. 

#Back substitution
x = np.empty(N,float)
for m in range(N-1,-1,-1):
    x[m] = B[m]
    for i in range (m+1,N):
        x[m] = x[m] - A[m,i]*x[i]
    
    

In [26]:
x

array([ 2., -1., -2.,  1.])

In [27]:
A

array([[ 1. ,  0.5,  2. ,  0.5],
       [ 0. ,  1. , -2.8, -1. ],
       [-0. , -0. ,  1. , -0. ],
       [-0. , -0. , -0. ,  1. ]])

In [28]:
B

array([-2. ,  3.6, -2. ,  1. ])